spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/employee_service
    username: hookup24
    password: hookup24
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
        ddl-auto: update
    show-sql: true
    properties:
        hibernate:
          dialect: org.hibernate.dialect.PostgreSQLDialect 
