springdoc:
  swagger-ui:
    path: /swagger/swagger.html
    operationSorter: method
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka
    register-with-eureka: true
    fetch-registry: true
  instance:
    preferIpAddress: true
security:
  oauth2:
    resource:
      jwt:
        key-value: hookup24