server:
  port: 0
spring:
  application:
        name: customer-service
  datasource:
    url: jdbc:postgresql://localhost:5432/customer
    username: hookup24
    password: hookup24
  jpa:
    hibernate:
        ddl-auto: update
    show-sql: true
    properties:
        hibernate:
          dialect: org.hibernate.dialect.PostgreSQLDialect 
security:
  oauth2:
    resource:
      jwt:
        key-value: hookup24
