eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761
    register-with-eureka: false
    fetch-registry: false
    registryFetchIntervalSeconds: 5
  instance.hostname: localhost
security:
  oauth2:
    resource:
      jwt.key-value: hookup24


