spring:
   jpa:
      hibernate:
          ddl-auto: create-drop
      show-sql: true
      properties:
          hibernate:
            dialect: org.hibernate.dialect.PostgreSQLDialect
   datasource:
      schema: classpath:/schema.sql
      url: jdbc:postgresql://postgres-db:5432/user_service
      username: hookup24
      password: hookup24
security:
  oauth2:
    resource:
      jwt:
        key-value: hookup24
