spring:
   jpa:
      hibernate:
          ddl-auto: update
      show-sql: true
      properties:
          hibernate:
            dialect: org.hibernate.dialect.PostgreSQLDialect
   datasource:
      schema: classpath:/schema.sql
      url: jdbc:postgresql://localhost:5432/user_service
      username: hookup24
      password: hookup24
