spring:
  cloud:
    gateway:
      default-filters:
        - TokenRelay
      routes:
      - id: auth-service
        uri: http://auth-service
        predicates:
        - Path=/auth-service/**
        filters:
            - RemoveRequestHeader=Cookie
      - id: courier-service
        uri: http://courier-service
        predicates:
        - Path=/courier-service/**
        filters:
            - RemoveRequestHeader=Cookie
      - id: user-service
        uri: http://user-service
        predicates:
        - Path=/user-service/**
        filters:
            - RemoveRequestHeader=Cookie
      - id: order-service
        uri: http://order-service
        predicates:
        - Path=/order-service/**
        filters:
            - RemoveRequestHeader=Cookie
