spring:
  cloud:
    gateway:
      routes:
      - id: auth-service
        uri: http://auth-service
        predicates:
        - Path=/auth-service/**
        - Header=Authorization, Basic password
      - id: courier-service
        uri: http://courier-service
        filters:
            - TokenRelay=
            - RemoveRequestHeader=Cookie
        predicates:
        - Path=/courier-service/**
        - Header=Authorization, Basic password
      - id: user-service
        uri: http://user-service
        filters:
            - TokenRelay=
            - RemoveRequestHeader=Cookie
        predicates:
        - Path=/user-service/**
        - Header=Authorization, Basic password
      - id: orders-service
        uri: http://orders-service
        filters:
            - TokenRelay=
            - RemoveRequestHeader=Cookie
        predicates:
        - Path=/orders-service/**
        - Header=Authorization, Basic password
