spring:
  cloud:
    gateway:
      routes:
#       - id: auth-service
#         uri: http://auth-service
#         predicates:
#         - Path=/auth-service/**
      - id: delivery-service
        uri: http://delivery-service
        predicates:
        - Path=/delivery-service/**
      - id: user-service
        uri: http://user-service
        predicates:
        - Path=/user-service/**
      - id: orders-service
        uri: http://orders-service
        filters:
            - TokenRelay=
            - RemoveRequestHeader=Cookie
        predicates:
        - Path=/orders-service/**
