spring:
  cloud:
    gateway:
      default-filters:
        - name: Retry
         args:
           retries: 3
           series: SERVER_ERROR
           statuses: BAD_GATEWAY,SERVICE_UNAVAILABLE,GATEWAY_TIMEOUT
           methods: GET,POST,PUT
           exceptions: org.springframework.cloud.gateway.support.NotFoundException,java.io.IOException,org.springframework.cloud.gateway.support.TimeoutException
           backoff: 
              firstBackoff: 50ms
              maxBackoff: 500ms
              factor: 2
              basedOnPreviousValue: false
      routes:
      - id: auth-service
        uri: http://auth-service
        predicates:
        - Path=/
        filters:
          - TokenRelay=
          - RemoveRequestHeader=Cookie
      - id: courier-service
        uri: http://courier-service
        predicates:
        - Path=/courier-service/**
        filters:
          - TokenRelay=
          - RemoveRequestHeader=Cookie
      - id: user-service
        uri: http://user-service
        predicates:
        - Path=/user-service/**
        filters:
          - TokenRelay=
          - RemoveRequestHeader=Cookie
      - id: order-service
        uri: http://order-service
        predicates:
        - Path=/order-service/**
        # filters:
        #   - TokenRelay=
        #   - RemoveRequestHeader=Cookie