spring:
  cloud:
    gateway:
      default-filters:
        - TokenRelay=
        - name: Retry
         args:
           retries: 3
           methods: GET
           series: SERVER_ERROR
           exceptions: java.io.IOException, java.util.concurrent.TimeoutException
           backoff: 
              firstBackoff: 50ms
              maxBackoff: 500ms
              factor: 2
              basedOnPreviousValue: false
      routes:
      - id: auth-service
        uri: http://auth-service
        predicates:
        - Path=/
          filters:
            - RemoveRequestHeader=Cookie
      - id: courier-service
        uri: http://courier-service
        predicates:
        - Path=/courier-service/**
          filters:
            - RemoveRequestHeader=Cookie
      - id: user-service
        uri: http://user-service
        predicates:
        - Path=/user-service/**
          filters:
            - RemoveRequestHeader=Cookie
      - id: order-service
        uri: http://order-service
        predicates:
        - Path=/order-service/**
        filters:
          - TokenRelay=
          - RemoveRequestHeader=Cookie

security:
  oauth2:
    resource:
      jwt:
        key-value: hookup24